#!/command/with-contenv bash

source /assets/functions/00-container
PROCESS_NAME="synapse"
prepare_service defaults single

check_container_initialized
check_service_initialized init

liftoff

print_start "Starting Synapse ${SYNAPSE_VERSION}"

exec s6-setuidgid synapse synctl --no-daemonize \
                                            start \
                                            ${CONFIG_PATH}
                                            #"${CONFIG_PATH}"/"${CONFIG_FILE}"

